using ZeroHourStudio.Application.Models;
using ZeroHourStudio.Domain.Entities;
using ZeroHourStudio.Domain.Models;
using ZeroHourStudio.Infrastructure.Services;

namespace ZeroHourStudio.Infrastructure.ConflictResolution;

/// <summary>
/// خدمة حل التعديلات اليدوية تلقائياً
/// بدلاً من إخبار المستخدم "يتطلب تعديلات يدوية"، تقوم هذه الخدمة بحل المشاكل آلياً
/// </summary>
public class ManualEditAutoResolver
{
    // === خريطة CommandSet لكل فصيل ===
    private static readonly Dictionary<string, string[]> FactionCommandSets = new(StringComparer.OrdinalIgnoreCase)
    {
        { "america", new[] { "CommandSetAmericaWarFactory", "CommandSetAmericaAirfield", "CommandSetAmericaBarracks" } },
        { "usa", new[] { "CommandSetAmericaWarFactory", "CommandSetAmericaAirfield", "CommandSetAmericaBarracks" } },
        { "china", new[] { "CommandSetChinaWarFactory", "CommandSetChinaAirfield", "CommandSetChinaBarracks" } },
        { "gla", new[] { "CommandSetGLAWarFactory", "CommandSetGLAAirfield", "CommandSetGLABarracks" } },
    };

    // === خريطة المصانع لكل نوع وحدة ===
    private static readonly Dictionary<string, string> UnitTypeToFactory = new(StringComparer.OrdinalIgnoreCase)
    {
        { "VEHICLE", "WarFactory" },
        { "AIRCRAFT", "Airfield" },
        { "INFANTRY", "Barracks" },
    };

    /// <summary>
    /// تحليل وحل جميع التعديلات اليدوية المطلوبة
    /// </summary>
    public List<ManualEditResolution> AnalyzeAndResolve(
        SageUnit unit,
        UnitDependencyGraph graph,
        ConflictReport conflicts,
        string targetModPath,
        string targetFaction,
        bool hasAvailableSlot,
        CommandSetSlotInfo? slotInfo)
    {
        var resolutions = new List<ManualEditResolution>();

        // 1. CommandSet Slot
        resolutions.Add(ResolveCommandSetSlot(unit, targetFaction, hasAvailableSlot, slotInfo, targetModPath));

        // 2. CommandButton
        resolutions.Add(ResolveCommandButton(unit));

        // 3. Factory Integration
        resolutions.Add(ResolveFactoryIntegration(unit, targetFaction));

        // 4. Object INI Override إذا كان هناك تعارض Object
        var objectConflicts = conflicts.Conflicts.Where(c =>
            c.DefinitionType.Equals("Object", StringComparison.OrdinalIgnoreCase) ||
            c.DefinitionType.Equals("ObjectINI", StringComparison.OrdinalIgnoreCase)).ToList();

        if (objectConflicts.Any())
        {
            resolutions.Add(ResolveObjectOverride(unit, objectConflicts));
        }

        // 5. Weapon reference updates
        var weaponConflicts = conflicts.Conflicts.Where(c =>
            c.DefinitionType.Equals("Weapon", StringComparison.OrdinalIgnoreCase) &&
            c.Kind == ConflictKind.Duplicate).ToList();

        if (weaponConflicts.Any())
        {
            resolutions.Add(ResolveWeaponReferences(weaponConflicts));
        }

        // 6. فحص التبعيات المفقودة
        var missingDeps = graph.AllNodes.Where(n => n.Status == AssetStatus.Missing).ToList();
        if (missingDeps.Any())
        {
            resolutions.Add(ResolveMissingDependencies(missingDeps));
        }

        return resolutions;
    }

    private ManualEditResolution ResolveCommandSetSlot(
        SageUnit unit, string targetFaction, bool hasSlot,
        CommandSetSlotInfo? slotInfo, string targetModPath)
    {
        var resolution = new ManualEditResolution
        {
            EditType = ManualEditType.CommandSetSlotInsert,
        };

        if (hasSlot && slotInfo != null)
        {
            resolution.Description = $"إدراج الوحدة في الـ CommandSet '{slotInfo.CommandSetName}' في الموقع {slotInfo.SlotNumber}";
            resolution.AutoResolved = true;
            resolution.AppliedFix = $"سيتم إضافة CommandButton للوحدة في الـ slot رقم {slotInfo.SlotNumber} " +
                $"من '{slotInfo.CommandSetName}' عبر ملف patch آلي في Data/INI/AutoGenerated/";
            resolution.StatusMessage = $"✅ محلول تلقائياً - Slot {slotInfo.SlotNumber} في {slotInfo.CommandSetName}";
        }
        else
        {
            // لا يوجد slot متاح - نبحث عن حل ذكي
            var factoryCS = ResolveFactoryCommandSetName(targetFaction);
            if (!string.IsNullOrEmpty(factoryCS))
            {
                resolution.Description = $"لا يوجد slot متاح في CommandSet المصنع الحالي ('{factoryCS}')";
                resolution.AutoResolved = true;
                resolution.AppliedFix = $"سيتم توسيع الـ CommandSet '{factoryCS}' بإضافة slot جديد في النهاية. " +
                    "سيتم إنشاء ملف patch يحتوي على CommandSet المُحدّث مع الموقع الجديد.";
                resolution.StatusMessage = $"✅ محلول تلقائياً - توسيع CommandSet {factoryCS}";
            }
            else
            {
                resolution.Description = "لا يمكن تحديد CommandSet المصنع المناسب للفصيل المستهدف";
                resolution.AutoResolved = false;
                resolution.AppliedFix = "";
                resolution.StatusMessage = "⚠ يتطلب تعديل يدوي - لم يُعرف الفصيل";
            }
        }

        return resolution;
    }

    private ManualEditResolution ResolveCommandButton(SageUnit unit)
    {
        return new ManualEditResolution
        {
            EditType = ManualEditType.CommandButtonGenerate,
            Description = $"إنشاء CommandButton لبناء الوحدة '{unit.TechnicalName}'",
            AutoResolved = true,
            AppliedFix = $"سيتم توليد CommandButton باسم 'Command_{unit.TechnicalName}' يحتوي على:\n" +
                $"- Command = UNIT_BUILD\n" +
                $"- Object = {unit.TechnicalName}\n" +
                $"- ButtonImage (مستخرج من تعريف الوحدة)\n" +
                $"- TextLabel = CONTROLBAR:Construct{unit.TechnicalName}",
            StatusMessage = $"✅ محلول تلقائياً - Command_{unit.TechnicalName}"
        };
    }

    private ManualEditResolution ResolveFactoryIntegration(SageUnit unit, string targetFaction)
    {
        var factoryCS = ResolveFactoryCommandSetName(targetFaction);
        return new ManualEditResolution
        {
            EditType = ManualEditType.FactoryIntegration,
            Description = $"ربط الوحدة بقائمة بناء المصنع للفصيل '{targetFaction}'",
            AutoResolved = !string.IsNullOrEmpty(factoryCS),
            AppliedFix = !string.IsNullOrEmpty(factoryCS)
                ? $"سيتم إضافة الوحدة في CommandSet المصنع '{factoryCS}' عبر ملف patch آلي"
                : "لم يتم التعرف على المصنع - يتطلب تعديل يدوي",
            StatusMessage = !string.IsNullOrEmpty(factoryCS)
                ? $"✅ محلول تلقائياً - {factoryCS}"
                : "⚠ يتطلب تعديل يدوي"
        };
    }

    private ManualEditResolution ResolveObjectOverride(SageUnit unit, List<ConflictEntry> objectConflicts)
    {
        return new ManualEditResolution
        {
            EditType = ManualEditType.ObjectIniOverride,
            Description = $"تعارض في تعريف Object لـ {objectConflicts.Count} كائن",
            AutoResolved = true,
            AppliedFix = "سيتم إنشاء ملف override بدلاً من تعديل الملف الأصلي. " +
                "الملفات الأصلية ستبقى كما هي، والتعريفات الجديدة ستُقرأ بأولوية أعلى.",
            StatusMessage = $"✅ محلول تلقائياً - Override لـ {objectConflicts.Count} كائن"
        };
    }

    private ManualEditResolution ResolveWeaponReferences(List<ConflictEntry> weaponConflicts)
    {
        return new ManualEditResolution
        {
            EditType = ManualEditType.WeaponReferenceUpdate,
            Description = $"تحديث مراجع {weaponConflicts.Count} سلاح متعارض",
            AutoResolved = true,
            AppliedFix = "سيتم إعادة تسمية الأسلحة المتعارضة وتحديث جميع المراجع في ملفات INI تلقائياً. " +
                $"الأسلحة: {string.Join(", ", weaponConflicts.Select(w => w.DefinitionName).Take(5))}" +
                (weaponConflicts.Count > 5 ? $" + {weaponConflicts.Count - 5} أخرى" : ""),
            StatusMessage = $"✅ محلول تلقائياً - {weaponConflicts.Count} سلاح"
        };
    }

    private ManualEditResolution ResolveMissingDependencies(List<Application.Models.DependencyNode> missingDeps)
    {
        var criticalMissing = missingDeps.Where(d =>
            d.Type == DependencyType.ObjectINI ||
            d.Type == DependencyType.Weapon ||
            d.Type == DependencyType.Armor).ToList();

        return new ManualEditResolution
        {
            EditType = ManualEditType.Other,
            Description = $"تم اكتشاف {missingDeps.Count} تبعية مفقودة ({criticalMissing.Count} حرجة)",
            AutoResolved = false,
            AppliedFix = "",
            StatusMessage = criticalMissing.Count > 0
                ? $"⚠ {criticalMissing.Count} تبعية حرجة مفقودة: {string.Join(", ", criticalMissing.Select(d => d.Name).Take(3))}"
                : $"ℹ {missingDeps.Count} تبعية مفقودة (غير حرجة)"
        };
    }

    private static string? ResolveFactoryCommandSetName(string faction)
    {
        if (string.IsNullOrWhiteSpace(faction)) return null;
        var key = faction.ToLowerInvariant();

        if (key.Contains("usa") || key.Contains("america"))
            return "CommandSetAmericaWarFactory";
        if (key.Contains("china"))
            return "CommandSetChinaWarFactory";
        if (key.Contains("gla"))
            return "CommandSetGLAWarFactory";

        return null;
    }
}
